#!/bin/bash
if ! command -v clang-format &> /dev/null
then
    echo "[warning] pre-commit: clang-format not found"
    exit
fi

echo "Running clang-format"
git diff --diff-filter=d --staged --name-only | grep -e '\(.*\).cpp$' -e '\(.*\).h$' | while read line; do
    echo "Formatting: $line"
    clang-format --style=file -i "$line"
    git add "$line"
done
